Use DateTimeImmutable by proper namespace
Seldaek/monolog pull request #1607
Opened 2021-11-02 13:46 UTC by curry684

With PHP 8.1 this results in:
```
Attempted to load class "DateTimeImmutable" from namespace "Monolog".
Did you forget a "use" statement for another namespace?
```

2021-11-02 14:49 UTC, juan-morales requested changes
maybe adding the dependency at the top with the **use** keyword is what we need

2021-11-02 14:49 UTC, juan-morales commented on src/Monolog/Logger.php
> +                    'datetime' => new \DateTimeImmutable($this->microsecondTimestamps, $this->timezone),
according to :

src/Monolog/Test/TestCase.php

it should be **Monolog\DateTimeImmutable**

2021-11-02 14:52 UTC, juan-morales requested changes

2021-11-02 14:52 UTC, juan-morales commented on src/Monolog/Logger.php
> +                    'datetime' => new \DateTimeImmutable($this->microsecondTimestamps, $this->timezone),
we need the usage of **Monolog\DateTimeImmutable** instead

2021-11-02 14:52 UTC, juan-morales commented on src/Monolog/Logger.php
> +                    'datetime' => new \DateTimeImmutable($this->microsecondTimestamps, $this->timezone),
we need the usage of **Monolog\DateTimeImmutable** instead

2021-11-02 14:52 UTC, juan-morales commented
According to this file:

src/Monolog/Test/TestCase.php

The right one is: **Monolog\DateTimeImmutable**

2021-11-02 14:53 UTC, juan-morales requested changes
Please use the right dependency

2021-11-02 14:54 UTC, juan-morales commented
sorry for all the comments, I got errors while doing the review and now I cannot delete duplicates.

2021-11-02 15:26 UTC, curry684 commented
Oh my you're completely right it never occurred to me there would be a local copy extending the global one. 

I'll dive into why the hell I'm getting that error then.

2021-11-02 15:26 UTC, closed without merging

2021-11-02 18:18 UTC, juan-morales commented
you can try adding at the top

**use Monolog\DateTimeImmutable** and leave DateTimeImmutable without the "\" symbol. Let me know if I can help you out on this. Welcome to help

2021-12-13 11:12 UTC, temp commented
Same problem here, but with docker. No caching occurs, still got the error in some projects. Error goes away if you require Monolog/DateTimeImmutable in index.php, but this is only a temporary quick fix.
We really have no clue what's the problem here, autoloading via composer looks fine.

2022-03-13 19:58 UTC, Seldaek commented
See https://github.com/Seldaek/monolog/issues/1626 and https://github.com/php/php-src/issues/8164  just in case you haven't yet.