return self on builder methods for more consistent behaviour
Seldaek/monolog pull request #1609
Opened 2021-11-16 21:51 UTC by codemasher

Just an example i just ran into:

```php
$formatter = (new LineFormatter)
    ->setJsonPrettyPrint(true) // -> LineFormatter instance
    ->addJsonEncodeOption(JSON_UNESCAPED_SLASHES) // -> void
    ->addJsonEncodeOption(JSON_UNESCAPED_UNICODE); // boo!
```

I didn't go through the handler classes to check for similar cases.

2021-11-18 08:51 UTC, juan-morales commented
In my own opinion, applying this pattern is nice, and gives us the possibility to write more readable code. Despite that, I believe that you should apply this pattern everywhere, at least all default formatters, to have a uniform code structure.

For example:

File: `src/Monolog/Formatter/LineFormatter.php` , is not on this change, and imo it should.

Can you please check a bit more in the code in order to apply uniformly this pattern wherever it needs to b applied? I also like this approach/pattern/style by the way.

2021-11-18 08:52 UTC, juan-morales requested changes
imo, there is/are missing place/s  as I pointed in my comment.

2021-11-18 09:03 UTC, codemasher commented
You're right, I've overlooked this (and probably more). Also, i was hesitant to change `Logger::reset()` and maybe even `Logger::close()`. I'll recheck when i got more time, also feel free to point out what I may have missed. :)

(Personally i despise public setter and builder methods that return `void` for no apparent reason and while this may [be opinionated](https://github.com/nikic/FastRoute/pull/181) (like almost everything in programming), maybe just let people have nice things?)

2022-03-07 13:24 UTC, merged

2022-03-07 13:24 UTC, Seldaek commented
Thanks