SlackWebhookHandler: use footer for username & footer_icon for userIcon
Seldaek/monolog pull request #1617
Opened 2021-11-26 20:31 UTC by whatUwant

related to https://github.com/Seldaek/monolog/issues/1247 & https://github.com/Seldaek/monolog/issues/1332

Since userIcon & username cannot be overridden, the text & smaller icon in footer can be used instead.

![custom-username](https://user-images.githubusercontent.com/2762992/143627373-a53e28c5-468e-4e4a-afb0-d405ddfbb93e.jpg)

2021-11-29 12:39 UTC, juan-morales requested changes
Even-though this seems ok, someone else has to check this also.

From my side, I kindly ask you to adjust all phpunit tests related to this change (there are some)

2021-11-29 12:44 UTC, juan-morales requested changes
adjust unit tests

2021-12-02 15:23 UTC, whatUwant commented
There are quite a few skipped tests. They all seem to be related to external database/cache thus do not concern `SlackWebhookHandler`.

```
PHPUnit 8.5.21 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.24-0ubuntu0.18.04.10 with Xdebug 2.6.0
Configuration: /var/www/html/monolog/phpunit.xml.dist

.............................................................   61 / 1114 (  5%)
...................................................SS........  122 / 1114 ( 10%)
...........S................SS......S........................  183 / 1114 ( 16%)
............................................S................  244 / 1114 ( 21%)
.............................................................  305 / 1114 ( 27%)
.............................................................  366 / 1114 ( 32%)
.............................................................  427 / 1114 ( 38%)
.............................................................  488 / 1114 ( 43%)
...................SS........................................  549 / 1114 ( 49%)
.............................................................  610 / 1114 ( 54%)
.............................................................  671 / 1114 ( 60%)
.............................................................  732 / 1114 ( 65%)
.............................................................  793 / 1114 ( 71%)
.............................................................  854 / 1114 ( 76%)
.............................................................  915 / 1114 ( 82%)
.............................................................  976 / 1114 ( 87%)
......S...................................................... 1037 / 1114 ( 93%)
............................................................. 1098 / 1114 ( 98%)
................                                              1114 / 1114 (100%)

Time: 3.07 seconds, Memory: 339.20 MB

There were 10 skipped tests:

1) Monolog\Handler\AmqpHandlerTest::testHandleAmqpExt
amqp-php not installed

/var/www/html/monolog/tests/Monolog/Handler/AmqpHandlerTest.php:26

2) Monolog\Handler\AmqpHandlerTest::testHandlePhpAmqpLib
php-amqplib not installed

/var/www/html/monolog/tests/Monolog/Handler/AmqpHandlerTest.php:82

3) Monolog\Handler\CouchDBHandlerTest::testHandle
Could not connect to couchdb server on http://localhost:5984

/var/www/html/monolog/tests/Monolog/Handler/CouchDBHandlerTest.php:28

4) Monolog\Handler\ElasticaHandlerTest::testHandleIntegration
Cannot connect to Elastic Search server on localhost

/var/www/html/monolog/tests/Monolog/Handler/ElasticaHandlerTest.php:192

5) Monolog\Handler\ElasticaHandlerTest::testHandleIntegrationNewESVersion
Cannot connect to Elastic Search server on localhost

/var/www/html/monolog/tests/Monolog/Handler/ElasticaHandlerTest.php:246

6) Monolog\Handler\ElasticsearchHandlerTest::testHandleIntegration
Cannot connect to Elasticsearch server on localhost

/var/www/html/monolog/tests/Monolog/Handler/ElasticsearchHandlerTest.php:210

7) Monolog\Handler\MongoDBHandlerTest::testHandleWithDriverManager
Could not connect to MongoDB server on mongodb://localhost:27017

/var/www/html/monolog/tests/Monolog/Handler/MongoDBHandlerTest.php:73

8) Monolog\Handler\ZendMonitorHandlerTest::testWrite
ZendServer is not installed

/var/www/html/monolog/tests/Monolog/Handler/ZendMonitorHandlerTest.php:24

9) Monolog\Handler\ZendMonitorHandlerTest::testGetDefaultFormatterReturnsNormalizerFormatter
ZendServer is not installed

/var/www/html/monolog/tests/Monolog/Handler/ZendMonitorHandlerTest.php:24

10) Monolog\Processor\MercurialProcessorTest::testProcessor
hg is missing

/var/www/html/monolog/tests/Monolog/Processor/MercurialProcessorTest.php:29

OK, but incomplete, skipped, or risky tests!
Tests: 1114, Assertions: 1896, Skipped: 10.
```

2021-12-04 08:41 UTC, juan-morales commented
Thanks! I will go through this and the rest of the pull requests tomorrow. Today I have a crazy day. 

Thanks for your effort

2021-12-13 16:14 UTC, juan-morales commented
sorry for the delay.

Question ... I cannot test this honestly ...but how does it look when you do have something like:

```
'footer' => null,
'footer_icon' => null,
```

in the attachments of a record, but they are NULL ... what will happen? I am worried that maybe Slack will complain, or the outlook will not be good. Can you tell me? In case of errors, should these fields be added in demand?

Someone else has an opinion on this?

OR

can you help me setting up my machine in order to test this ? What do I need?

2021-12-13 16:17 UTC, whatUwant commented
> sorry for the delay.
> 
> Question ... I cannot test this honestly ...but how does it look when you do have something like:
> 
> ```
> 'footer' => null,
> 'footer_icon' => null,
> ```
> 
> in the attachments of a record, but they are NULL ... what will happen?

The content in the green box disappears. Only time is present.
![custom-username](https://user-images.githubusercontent.com/2762992/143627373-a53e28c5-468e-4e4a-afb0-d405ddfbb93e.jpg)

2021-12-14 07:06 UTC, juan-morales approved these changes

2021-12-14 07:08 UTC, juan-morales commented
Thanks for Your effort. I believe @Seldaek organización another mánager will join during this Week maybe to take Care about the pull requests in the queue. 

Have a great day

2022-03-13 19:29 UTC, Seldaek commented
Thanks

2022-03-13 19:29 UTC, merged